baseURL = 'https://braxmeierandreas.github.io/BLOG/'
languageCode = 'de-de'
title = 'Andreas Braxmeier'
theme = "PaperMod"
paginate = 10

[params]
  defaultTheme = "auto" # dark, light, auto
  description = "Master-Student | Tech-Enthusiast | Furtwangen"
  author = "Andreas Braxmeier"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  
  [params.homeInfoParams]
    Title = "Hi, ich bin Andreas ðŸ‘‹"
    Content = "Willkommen auf meinem Blog. Hier schreibe ich Ã¼ber Tech, mein Studium und alles, was mich bewegt."

  [params.socialIcons]
    github = "https://github.com/braxmeierandreas"
    # linkedin = "https://linkedin.com/in/..."

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "Ãœber mich"
    url = "/about/"
    weight = 20

# Syntax Highlighting (fÃ¼r Code-BlÃ¶cke)
[markup]
  [markup.highlight]
    noClasses = false