baseurl = "https://braxmeierandreas.github.io/BLOG/"
languageCode = "de-de"
title = "Andreas Braxmeier"
theme = "Niello"
paginate = 10

[params]
  author = "Andreas Braxmeier"
  description = "Master-Student | Tech-Enthusiast | Furtwangen"
  
  # Theme Settings
  defaultTheme = "auto" # or "dark" or "light"
  
  # Header
  [params.header]
    logo = "Andreas Braxmeier"
    
  # Footer
  [params.footer]
    copyright = "© 2026 Andreas Braxmeier"

[menu]
  [[menu.main]]
    name = "Startseite"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts"
    weight = 2
  [[menu.main]]
    name = "Über mich"
    url = "/about"
    weight = 3
    
[markup]
  [markup.highlight]
    # style = "github-dark"
