baseURL = 'https://braxmeierandreas.github.io/BLOG/'
languageCode = 'de-de'
title = 'Andreas Braxmeier'
theme = "PaperMod"
[pagination]
  pagerSize = 10

[params]
  defaultTheme = "auto"
  description = "Master-Student | Tech-Enthusiast | Furtwangen"
  author = "Andreas Braxmeier"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon.png"
    favicon32x32 = "/favicon.png"
    apple_touch_icon = "/apple-touch-icon.png"
  
  [params.homeInfoParams]
    Title = "Hi, ich bin Andreas ðŸ‘‹"
    Content = "Willkommen auf meinem Blog. Hier schreibe ich Ã¼ber Tech, mein Studium und alles, was mich bewegt."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/braxmeierandreas"


[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "Ãœber mich"
    url = "/about/"
    weight = 20

# Syntax Highlighting (fÃ¼r Code-BlÃ¶cke)
[markup]
  [markup.highlight]
    noClasses = false
