baseURL = 'https://braxmeierandreas.github.io/BLOG/'
languageCode = 'de-de'
title = 'Andreas Braxmeier'
theme = 'docura'
[pagination]
  pagerSize = 10

[params]
  description = "Master-Student | Tech-Enthusiast | Furtwangen"
  
  [params.author]
    name = "Andreas Braxmeier"
  
  # Docura specific settings
  [params.ui]
    theme = "" # light, dark, auto

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts"
    weight = 2
  [[menu.main]]
    name = "Ãœber mich"
    url = "/about"
    weight = 3
